//Class CalculatorClass developed by KB
//************************************************************** */
// version   Developer   Date       Description 
// V1.2      KB          09.11.21   Division Method implemented
//************************************************************** */
public class CalculatorClass {
    //Constructor
    public class CalculatorClass {
    }

    public double Addition(Double num1,Double num2) {
        return num1 + num2;
    }

    public double Substraction(Double num1,Double num2) {
        return num1 - num2;
    }

    public double Division(Double num1,Double num2) {
        return num1 / num2;
    }
}
